blueprint:
  name: Motion activated light
  description: Turn on a light when motion is detected and turn it off when no motion is detected for a certain period of time. Does not trigger if the light is already on.
  domain: automation
  input:
    motion_sensor:
      name: Motion Sensor
      description: The motion sensor that triggers the light
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    light_entity:
      name: Light
      description: The light to be controlled
      selector:
        entity:
          domain: light
    no_motion_wait:
      name: No motion wait time
      description: The amount of time to wait when no motion is detected before turning off the light
      default: 300
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds

trigger:
  - platform: state
    entity_id: !input 'motion_sensor'
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: !input 'motion_sensor'
    from: 'clear'
    to: 'detected'

condition:
  condition: state
  entity_id: !input 'light_entity'
  state: 'off'

action:
  - service: light.turn_on
    target:
      entity_id: !input 'light_entity'
  - wait_for_trigger:
      - platform: state
        entity_id: !input 'motion_sensor'
        from: 'on'
        to: 'off'
        for: 
          seconds: !input 'no_motion_wait'
      - platform: state
        entity_id: !input 'motion_sensor'
        from: 'detected'
        to: 'clear'
        for: 
          seconds: !input 'no_motion_wait'
  - service: light.turn_off
    target:
      entity_id: !input 'light_entity'
