blueprint:
  name: Motion activated light with time-based brightness
  description: Turn on a light when motion is detected and turn it off when no motion is detected for a certain period of time. The brightness and transition time of the light are adjusted based on the time of day.
  domain: automation
  input:
    motion_sensor:
      name: Motion Sensor
      description: The motion sensor that triggers the light
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    light_entity:
      name: Light
      description: The light to be controlled
      selector:
        entity:
          domain: light
    no_motion_wait:
      name: No motion wait time
      description: The amount of time to wait when no motion is detected before turning off the light
      default: 300
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds

trigger:
  platform: state
  entity_id: !input 'motion_sensor'
  from: 'off'
  to: 'on'

condition:
  condition: state
  entity_id: !input 'light_entity'
  state: 'off'

action:
  - variables:
      transition_time: >
        {% if now().hour < state_attr('sun.sun', 'next_rising').hour + 1 or now().hour > state_attr('sun.sun', 'next_setting').hour - 1 %}
          60
        {% else %}
          5
        {% endif %}
  - service: light.turn_on
    target:
      entity_id: !input 'light_entity'
    data:
      brightness: 255
      transition: "{{ transition_time }}"
  - wait_for_trigger:
      platform: state
      entity_id: !input 'motion_sensor'
      from: 'on'
      to: 'off'
      for: 
        seconds: !input 'no_motion_wait'
  - service: light.turn_off
    target:
      entity_id: !input 'light_entity'
